### PR TITLE
A wave sampler replacing the MIDI output

### PR DESCRIPTION
**Pull request by jmiskovic**
This is a draft with working drum sound, not really merge-able.

It needs a better drumkit sample set. I just grabbed what I had to make it work.
The sampler is ripped from guts of the Hexpress app and adapted for LOVR.

It doesn't support multiple samples per same trigger, but sampler already supports velocity. A rich drumkit sample set could have multiple samples per kit element and they would be used for different note velocities. The included sample set doesn't have them :(

The sampler has ADSR enveloping which is effectively disabled in the sampler instance settings. It would be useful if you wanted to expand to synths. There is also unused pitch calculation for tonal instruments, these drum samples just have the default pitch.

Code partially implements the same API as RtMidi Lua API as used in the drummer app. For now it is just plugged in place of MIDI driver, but there should probably be a "bus" in between to duplicate the MIDI messages between the two.

Also, I noticed sounds are triggered twice; IMO the second trigger should be a noteOff message instead. You cannot hear them with the sampler because their velocity is zero, but they take up from the sampler pool.

Does it work on your side?

### CODE REVIEW

**Comment by immortalx74** [comment]
Nice work, thank you! It works on my side (with just a minor fix on line 82: changed Vec3 to lower case vec3).
I was working on supporting build-in sounds but got stuck on trying to find a free drumkit that includes tip/edge & center/rim samples for cymbals/drums, and multiple samples per sound, as you mentioned.
About the sounds getting triggered twice: Since I was only sending MIDI, a noteOn with zero velocity is translated to noteOff effectively, so it didn't matter. But I'll have to change it to work with the sampler (so that `MIDIctrl.noteOff` gets called).
The implementation I was working on relied on a user preference (in the ui) to either work in MIDI-out mode or build-in sounds. I think it makes more sense this way.

**Comment by jmiskovic** [comment]
You are correct, both note off and vel=0 note on should stop the sample, I fixed this on the sampler side.

The UI user preference is of course a necessary step. I was proposing a virtual MIDI bus (or router)  because this is the usual mechanism in DAWs. With such decoupling you could also hook up an external MIDI footswitch as additional MIDI source to be used for the kick drum trigger.

Naturally your own implementation will work best for maintaining the code and supporting the features you would like to see. I'm keeping my eye because with these building blocks it becomes possible to make crazy innovative 3D instruments and workflows.

**Comment by immortalx74** [comment]
I'll have a working implementation ready in a couple of days. The hard thing was finding a free drumkit with enough samples per piece. Again thank you so much for the help!

**Comment by immortalx74** [comment]
Thanks a lot for the original idea, I finally did an implementation. It isn't as sophisticated but it will do for now. Thank you again!

**Pull request closed without merging**
